backend/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('people_manager.urls')),
    path('vue_manager/', include('vue_manager.urls')),
    path('admin/', admin.site.urls),
]

backend/people_manager/urls.py
from django.urls import path
from . import views

app_name = 'people_manager'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.show, name='show'),
    path('new/', views.new, name='new'),
    path('search/', views.search, name='search')
]

backend/vue_manager/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from vue_manager import views

app_name = 'vue_manager'
urlpatterns = [
    path('', views.PersonList.as_view())
]

urlpatterns = format_suffix_patterns(urlpatterns)

backend/people_manager/models.py
from django.db import models

class Person(models.Model):
    name = models.CharField(max_length = 50)
    email = models.EmailField()

backend/vue_manager/models.py
from django.db import models

# Create your models here.

backend/people_manager/forms.py
from django import forms
from .models import Person

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['name', 'email']

backend/people_manager/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Person
from .forms import PersonForm

def index(request):
    people = Person.objects.order_by('name')
    context = {'people': people, 'form': PersonForm()}
    return render(request, 'people_manager/index.html', context)

def show(request, id):
    person = get_object_or_404(Person, pk=id)
    return render(request, 'people_manager/show.html', {'person': person})

def new(request):
    if request.method == 'POST':
        person = PersonForm(request.POST)
        if person.is_valid():
            person.save()
            return HttpResponseRedirect(reverse('people_manager:index'))
    else:
        return render(
            request,
            'people_manager/new.html',
            {'form': PersonForm()}
        )

def search(request):
    name = request.GET.get('name', '')
    email = request.GET.get('email', '')
    form = PersonForm(initial={'name': name, 'email': email})
    people = Person.objects.filter(name=name, email=email)
    return render(
        request,
        'people_manager/search.html',
        {
            'people': people,
            'form': form,
            'search': { 'name': name, 'email': email }
        }
    )

backend/vue_manager/views.py
from people_manager.models import Person
from vue_manager.serializers import PersonSerializer
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

class PersonList(APIView):
    """
    List all people, or create a new person.
    """
    def get(self, request, format=None):
        person = Person.objects.all()
        serializer = PersonSerializer(person, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = PersonSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

backend/people_manager/templates/people_manager/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> People Manager | Django</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container" style="text-align:center">
      <h1 style="display:inline-block"> People Manager | Django </h1>
      <div>
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

backend/people_manager/templates/people_manager/index.html
{% extends 'people_manager/base.html' %}

{% block content %}
<!-- person search -->
<form action="/search" method="get">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Search" />
</form>
<!-- end of person search -->
<!-- people list -->
<ul class="list-group">
  <li class="list-group-item">
    <a href="{% url 'people_manager:new' %}">
      Create new person
    </a>
  </li>
  {% if people %}
    {% for person in people %}
        <li class="list-group-item">
          <span class="font-weight-bold">name: </span>
          <span>
              {{ person.name }}
          </span>
          <span class="font-weight-bold">email: </span>
          <span>
            {{person.email}}
          </span>
          <a href="{% url 'people_manager:show' person.id %}" style="text-decoration:none">
            View
          </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No people are available.</p>
{% endif %}
{% endblock %}

backend/people_manager/templates/people_manager/new.html
{% extends 'people_manager/base.html' %}

{% block content %}
<p class="font-weight-bold">
  Create Person
</p>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
<a href="{% url 'people_manager:index' %}">
  <button type="button" class="btn" style="margin-top:20px">
    Cancel
  </button>
</a>
{% endblock %}

backend/people_manager/templates/people_manager/search.html
{% extends 'people_manager/base.html' %}

{% block content %}
<p class="font-weight-bold">
  Search People
</p>
<!-- person search -->
<form action="/search" method="get">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Search" />
</form>
<!-- end of person search -->
{% if people %}
    <ul class="list-group">
    {% for person in people %}
        <li class="list-group-item">
          <span class="font-weight-bold">name:</span>
          <span>
            {{ person.name }}
          </span>
          <span class="font-weight-bold">email:</span>
          <span>
            {{person.email}}
          </span>
          <a href="{% url 'people_manager:show' person.id %}" style="text-decoration:none">
            View
          </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No records were found with these search parameters.</p>
{% endif %}
<a href="{% url 'people_manager:index' %}">
  <button type="button" class="btn" style="margin-top:20px">
    Back
  </button>
</a>
{% endblock %}

backend/people_manager/templates/people_manager/show.html
{% extends 'people_manager/base.html' %}

{% block content %}
<p class="font-weight-bold">
  View Person
</p>
<ul class="list-group">
  <li class="list-group-item">
    id: {{person.id}}
  </li>
  <li class="list-group-item">
    name: {{ person.name }}
  </li>
  <li class="list-group-item">
    email: {{person.email}}
  </li>
</ul>
<a href="{% url 'people_manager:index' %}">
  <button type="button" class="btn" style="margin-top:20px">
    Back
  </button>
</a>
{% endblock %}